baseurl: "https://xd-con.org/imagexd-2019"
title: "ImageXD 2019"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "ImageXD 2019"
  Description: "Images Across Domains"
  Date: "September 11–13"
  # Price: "Only $100"  # If your event is free, just comment this line
  Venue: "Berkeley Institute for Data Science"
  Address: "190 Doe Library, UC Berkeley Campus"
  City:  "Berkeley"
  State: "California"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - during
    - about
#    - timeline
#    - speakers
    - schedule
    - location
    - sponsors
    - organizers
#    - contact

  # Titles which you can translate to other languages
  Titles:
    during: "Welcome!"
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    organizers: "Organizers"
    timeline: "Timeline"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
#  CallToAction:
#    text: "Apply Now"
#    link: "https://forms.gle/KdML1iRTFBp1WpNx7"

  # List of Sponsors
  Sponsors:
    - name: "Berkeley Institute for Data Science"
      logo: "/img/BIDS.png"
      url: "https://bids.berkeley.edu"

  Timeline:
    - date: 28 May
      action: Registration opens

    - date: 31 July
      action: Registration closes (extended)

    - date: 30 July
      action: Participant selection announced

  EventLinks:
    - title: "Schedule"
      url: "#schedule"
    - title: "Agenda & running notes"
      url: "https://hackmd.io/m502u6NsQzGi1GaIyXMtnQ"
    - title: "Proceedings"
      url: "https://dani-lbnl.github.io/"
    - title: "Code of Conduct"
      url: "/code-of-conduct"

  # The entire schedule
  Schedule:
    - day: "Wednesday (11 Sep)"
      slots:
        - name: "— Check-in / Breakfast —"
          time: "08:50–09:00"
        - name: "Welcome"
          time: "09:00–09:15"
          presenter: "David Mongeau"
        - name: "scikit-image: Introduction"
          time: "09:15–10:10"
          url: "https://github.com/imagexd/2019-tutorial-skimage"
          presenter: "Stéfan van der Walt"
        - name: "scikit-image: 3D Image Processing"
          time: "10:20–12:30"
          presenter: "Dani Ushizima, Alex de Siqueira"
          url: "https://github.com/imagexd/2019-tutorial-skimage"
        - name: "— Lunch —"
          time: "12:30–14:00"
        - name: "Neural Networks"
          time: "14:00–15:30"
          presenter: "Ariel Rokem, Henry Pinkard"
          url: "https://tinyurl.com/imagexd2019-convnets"
        - name: "— Tea break —"
          time: "15:30–15:45"
        - name: "Volume Registration"
          time: "16:00–17:30"
          presenter: "Maryana Alegro, Matt McCormick"
          url: "https://github.com/KitwareMedical/2019-ImageXD-Registration-Tutorial"

    - day: "Thursday (12 Sep)"
      slots:
        - name: "Breakfast"
          time: "08:50–09:00"
        - name: "Welcome & logistics"
          time: "09:00–09:10"
          presenter: "Dani Ushizima"
        - name: "Spatiotemporally adaptive imaging with smart microscopy"
          time: "09:10–9:40"
          presenter: "Loic Royer"
        - name: "Neural network-controlled microscopy and optimization-based image registration"
          presenter: "Henry Pinkard"
          time: "09:40–10:00"
        - name: "Napari: multi-dimensional image visualization in Python"
          presenter: "Kira Evans"
          time: "10:00–10:20"
        - name: "Global scale observation using satellite imagery and machine learning"
          presenter: "Esther Rolf"
          time: "10:20–10:40"
        - name: "— Break —"
          time: "10:40–11:10"
        - name: "Microscopy image analysis"
          presenter: "Cedric Espenel"
          time: "11:10–11:30"
        - name: "Lights! Camera! Extraction! ML methods for when your data is ready for prime time"
          presenter: "Pablo Damasceno"
          time: "11:30–11:50"
        - name: "Working with multidimensional microscopy images in Julia"
          presenter: "Tamas Nagy"
          time: "11:50–12:10"
        - name: ""
          name: "— Lunch —"
          time: "12:10–13:10"
        - name: ""
          name: "— Collaborative Work —"
          time: "13:10–17:30"

    - day: "Friday (13 Sep)"
      slots:
        - name: "Breakfast"
          time: "08:50–09:00"
        - name: "Logistics"
          time: "09:00–09:10"
        - name: "Imaging complex biological machines in action"
          time: "09:10–9:40"
          presenter: "Carolyn Larabell"
        - name: "Invited Talk, TBA"
          presenter: "Matthew Rocklin"
          time: "09:40–10:00"
        - name: "Slideslicer: a package for manipulation of whole slide imaging and annotations"
          presenter: "Dima Lituiev"
          time: "10:00–10:20"
        - name: "Modeling flexibility in macromolecular structures obtained by cryo-electron microscopy"
          presenter: "Iris Young"
          time: "10:20–10:40"
        - name: "— Break —"
          time: "10:40–11:10"
        - name: "Data driven design for computational microscopy"
          presenter: "Michael Kellman"
          time: "11:10–11:30"
        - name: "Convolutional Neural Networks of Fiber Detection models"
          presenter: "Silvia Miramontes"
          time: "11:30–11:50"
        - name: "Recognizing the Impossible Image: How 3D Imaging Can Lead to Optical Character Recognition for Cuneiform Tablets"
          presenter: "Adam Anderson"
          time: "11:50–12:10"
        - name: ""
          name: "— Lunch —"
          time: "12:10–13:10"
        - name: "— Collaborative Work —"
          time: "13:10–16:00"
        - name: "— Lightning Talks —"
          time: "16:00–17:30"

    # - name: "Linus Torvalds"
    #   photo: "/img/speaker.jpg"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Linux Foundation"
    #   link:
    #     href: "http://twitter.com/linus"
    #     text: "@linus"
    #   presentation:
    #     title: "Digging into a Linux Kernel"
    #     description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #     time: "10h00"

  Organizers:
    - name: "Daniela Ushizima"
      affiliation: "LBNL / UC Berkeley"
    - name: "Maryana Alegro"
      affiliation: "UCSF / UC Berkeley"
    - name: "Kevin Keys"
      affiliation: "UCSF / UC Berkeley"
    - name: "Henry Pinkard"
      affiliation: "UC Berkeley"
    - name: "Stéfan van der Walt"
      affiliation: "UC Berkeley"
